//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sp.Service.SpServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.sp.com/", ConfigurationName="SpServiceReference.ISpService")]
    public interface ISpService {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Sp.Service.SpServiceReference.getBarCodeResponse getBarCode(Sp.Service.SpServiceReference.getBarCode request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Sp.Service.SpServiceReference.getFinanciallistServiceResponse getFinanciallistService(Sp.Service.SpServiceReference.getFinanciallistService request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Sp.Service.SpServiceReference.getAllTrackListServiceResponse getAllTrackListService(Sp.Service.SpServiceReference.getAllTrackListService request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Sp.Service.SpServiceReference.orderServiceResponse orderService(Sp.Service.SpServiceReference.orderService request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Sp.Service.SpServiceReference.getHtmlLableResponse getHtmlLable(Sp.Service.SpServiceReference.getHtmlLable request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Sp.Service.SpServiceReference.getTrackListServiceResponse getTrackListService(Sp.Service.SpServiceReference.getTrackListService request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Sp.Service.SpServiceReference.getlogoimagestrResponse getlogoimagestr(Sp.Service.SpServiceReference.getlogoimagestr request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Sp.Service.SpServiceReference.orderConfirmServiceResponse orderConfirmService(Sp.Service.SpServiceReference.orderConfirmService request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Sp.Service.SpServiceReference.downFinancialFileResponse downFinancialFile(Sp.Service.SpServiceReference.downFinancialFile request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Sp.Service.SpServiceReference.batchOrderServiceResponse batchOrderService(Sp.Service.SpServiceReference.batchOrderService request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBarCode {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBarCode", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.getBarCodeBody Body;
        
        public getBarCode() {
        }
        
        public getBarCode(Sp.Service.SpServiceReference.getBarCodeBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getBarCodeBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public getBarCodeBody() {
        }
        
        public getBarCodeBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBarCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBarCodeResponse", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.getBarCodeResponseBody Body;
        
        public getBarCodeResponse() {
        }
        
        public getBarCodeResponse(Sp.Service.SpServiceReference.getBarCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getBarCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getBarCodeResponseBody() {
        }
        
        public getBarCodeResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFinanciallistService {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFinanciallistService", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.getFinanciallistServiceBody Body;
        
        public getFinanciallistService() {
        }
        
        public getFinanciallistService(Sp.Service.SpServiceReference.getFinanciallistServiceBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFinanciallistServiceBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public getFinanciallistServiceBody() {
        }
        
        public getFinanciallistServiceBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFinanciallistServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFinanciallistServiceResponse", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.getFinanciallistServiceResponseBody Body;
        
        public getFinanciallistServiceResponse() {
        }
        
        public getFinanciallistServiceResponse(Sp.Service.SpServiceReference.getFinanciallistServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFinanciallistServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getFinanciallistServiceResponseBody() {
        }
        
        public getFinanciallistServiceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllTrackListService {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllTrackListService", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.getAllTrackListServiceBody Body;
        
        public getAllTrackListService() {
        }
        
        public getAllTrackListService(Sp.Service.SpServiceReference.getAllTrackListServiceBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getAllTrackListServiceBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public getAllTrackListServiceBody() {
        }
        
        public getAllTrackListServiceBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllTrackListServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllTrackListServiceResponse", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.getAllTrackListServiceResponseBody Body;
        
        public getAllTrackListServiceResponse() {
        }
        
        public getAllTrackListServiceResponse(Sp.Service.SpServiceReference.getAllTrackListServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getAllTrackListServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getAllTrackListServiceResponseBody() {
        }
        
        public getAllTrackListServiceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class orderService {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="orderService", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.orderServiceBody Body;
        
        public orderService() {
        }
        
        public orderService(Sp.Service.SpServiceReference.orderServiceBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class orderServiceBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public orderServiceBody() {
        }
        
        public orderServiceBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class orderServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="orderServiceResponse", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.orderServiceResponseBody Body;
        
        public orderServiceResponse() {
        }
        
        public orderServiceResponse(Sp.Service.SpServiceReference.orderServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class orderServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public orderServiceResponseBody() {
        }
        
        public orderServiceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHtmlLable {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHtmlLable", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.getHtmlLableBody Body;
        
        public getHtmlLable() {
        }
        
        public getHtmlLable(Sp.Service.SpServiceReference.getHtmlLableBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getHtmlLableBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public getHtmlLableBody() {
        }
        
        public getHtmlLableBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHtmlLableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHtmlLableResponse", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.getHtmlLableResponseBody Body;
        
        public getHtmlLableResponse() {
        }
        
        public getHtmlLableResponse(Sp.Service.SpServiceReference.getHtmlLableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getHtmlLableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getHtmlLableResponseBody() {
        }
        
        public getHtmlLableResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTrackListService {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTrackListService", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.getTrackListServiceBody Body;
        
        public getTrackListService() {
        }
        
        public getTrackListService(Sp.Service.SpServiceReference.getTrackListServiceBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getTrackListServiceBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public getTrackListServiceBody() {
        }
        
        public getTrackListServiceBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTrackListServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTrackListServiceResponse", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.getTrackListServiceResponseBody Body;
        
        public getTrackListServiceResponse() {
        }
        
        public getTrackListServiceResponse(Sp.Service.SpServiceReference.getTrackListServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getTrackListServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getTrackListServiceResponseBody() {
        }
        
        public getTrackListServiceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getlogoimagestr {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getlogoimagestr", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.getlogoimagestrBody Body;
        
        public getlogoimagestr() {
        }
        
        public getlogoimagestr(Sp.Service.SpServiceReference.getlogoimagestrBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getlogoimagestrBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public getlogoimagestrBody() {
        }
        
        public getlogoimagestrBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getlogoimagestrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getlogoimagestrResponse", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.getlogoimagestrResponseBody Body;
        
        public getlogoimagestrResponse() {
        }
        
        public getlogoimagestrResponse(Sp.Service.SpServiceReference.getlogoimagestrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getlogoimagestrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getlogoimagestrResponseBody() {
        }
        
        public getlogoimagestrResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class orderConfirmService {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="orderConfirmService", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.orderConfirmServiceBody Body;
        
        public orderConfirmService() {
        }
        
        public orderConfirmService(Sp.Service.SpServiceReference.orderConfirmServiceBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class orderConfirmServiceBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public orderConfirmServiceBody() {
        }
        
        public orderConfirmServiceBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class orderConfirmServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="orderConfirmServiceResponse", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.orderConfirmServiceResponseBody Body;
        
        public orderConfirmServiceResponse() {
        }
        
        public orderConfirmServiceResponse(Sp.Service.SpServiceReference.orderConfirmServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class orderConfirmServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public orderConfirmServiceResponseBody() {
        }
        
        public orderConfirmServiceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downFinancialFile {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downFinancialFile", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.downFinancialFileBody Body;
        
        public downFinancialFile() {
        }
        
        public downFinancialFile(Sp.Service.SpServiceReference.downFinancialFileBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class downFinancialFileBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public downFinancialFileBody() {
        }
        
        public downFinancialFileBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downFinancialFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downFinancialFileResponse", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.downFinancialFileResponseBody Body;
        
        public downFinancialFileResponse() {
        }
        
        public downFinancialFileResponse(Sp.Service.SpServiceReference.downFinancialFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class downFinancialFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public downFinancialFileResponseBody() {
        }
        
        public downFinancialFileResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class batchOrderService {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="batchOrderService", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.batchOrderServiceBody Body;
        
        public batchOrderService() {
        }
        
        public batchOrderService(Sp.Service.SpServiceReference.batchOrderServiceBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class batchOrderServiceBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public batchOrderServiceBody() {
        }
        
        public batchOrderServiceBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class batchOrderServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="batchOrderServiceResponse", Namespace="http://service.sp.com/", Order=0)]
        public Sp.Service.SpServiceReference.batchOrderServiceResponseBody Body;
        
        public batchOrderServiceResponse() {
        }
        
        public batchOrderServiceResponse(Sp.Service.SpServiceReference.batchOrderServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class batchOrderServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public batchOrderServiceResponseBody() {
        }
        
        public batchOrderServiceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISpServiceChannel : Sp.Service.SpServiceReference.ISpService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SpServiceClient : System.ServiceModel.ClientBase<Sp.Service.SpServiceReference.ISpService>, Sp.Service.SpServiceReference.ISpService {
        
        public SpServiceClient() {
        }
        
        public SpServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sp.Service.SpServiceReference.getBarCodeResponse Sp.Service.SpServiceReference.ISpService.getBarCode(Sp.Service.SpServiceReference.getBarCode request) {
            return base.Channel.getBarCode(request);
        }
        
        public string getBarCode(string arg0, string arg1) {
            Sp.Service.SpServiceReference.getBarCode inValue = new Sp.Service.SpServiceReference.getBarCode();
            inValue.Body = new Sp.Service.SpServiceReference.getBarCodeBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            Sp.Service.SpServiceReference.getBarCodeResponse retVal = ((Sp.Service.SpServiceReference.ISpService)(this)).getBarCode(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sp.Service.SpServiceReference.getFinanciallistServiceResponse Sp.Service.SpServiceReference.ISpService.getFinanciallistService(Sp.Service.SpServiceReference.getFinanciallistService request) {
            return base.Channel.getFinanciallistService(request);
        }
        
        public string getFinanciallistService(string arg0, string arg1) {
            Sp.Service.SpServiceReference.getFinanciallistService inValue = new Sp.Service.SpServiceReference.getFinanciallistService();
            inValue.Body = new Sp.Service.SpServiceReference.getFinanciallistServiceBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            Sp.Service.SpServiceReference.getFinanciallistServiceResponse retVal = ((Sp.Service.SpServiceReference.ISpService)(this)).getFinanciallistService(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sp.Service.SpServiceReference.getAllTrackListServiceResponse Sp.Service.SpServiceReference.ISpService.getAllTrackListService(Sp.Service.SpServiceReference.getAllTrackListService request) {
            return base.Channel.getAllTrackListService(request);
        }
        
        public string getAllTrackListService(string arg0, string arg1) {
            Sp.Service.SpServiceReference.getAllTrackListService inValue = new Sp.Service.SpServiceReference.getAllTrackListService();
            inValue.Body = new Sp.Service.SpServiceReference.getAllTrackListServiceBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            Sp.Service.SpServiceReference.getAllTrackListServiceResponse retVal = ((Sp.Service.SpServiceReference.ISpService)(this)).getAllTrackListService(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sp.Service.SpServiceReference.orderServiceResponse Sp.Service.SpServiceReference.ISpService.orderService(Sp.Service.SpServiceReference.orderService request) {
            return base.Channel.orderService(request);
        }
        
        public string orderService(string arg0, string arg1) {
            Sp.Service.SpServiceReference.orderService inValue = new Sp.Service.SpServiceReference.orderService();
            inValue.Body = new Sp.Service.SpServiceReference.orderServiceBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            Sp.Service.SpServiceReference.orderServiceResponse retVal = ((Sp.Service.SpServiceReference.ISpService)(this)).orderService(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sp.Service.SpServiceReference.getHtmlLableResponse Sp.Service.SpServiceReference.ISpService.getHtmlLable(Sp.Service.SpServiceReference.getHtmlLable request) {
            return base.Channel.getHtmlLable(request);
        }
        
        public string getHtmlLable(string arg0, string arg1) {
            Sp.Service.SpServiceReference.getHtmlLable inValue = new Sp.Service.SpServiceReference.getHtmlLable();
            inValue.Body = new Sp.Service.SpServiceReference.getHtmlLableBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            Sp.Service.SpServiceReference.getHtmlLableResponse retVal = ((Sp.Service.SpServiceReference.ISpService)(this)).getHtmlLable(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sp.Service.SpServiceReference.getTrackListServiceResponse Sp.Service.SpServiceReference.ISpService.getTrackListService(Sp.Service.SpServiceReference.getTrackListService request) {
            return base.Channel.getTrackListService(request);
        }
        
        public string getTrackListService(string arg0, string arg1) {
            Sp.Service.SpServiceReference.getTrackListService inValue = new Sp.Service.SpServiceReference.getTrackListService();
            inValue.Body = new Sp.Service.SpServiceReference.getTrackListServiceBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            Sp.Service.SpServiceReference.getTrackListServiceResponse retVal = ((Sp.Service.SpServiceReference.ISpService)(this)).getTrackListService(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sp.Service.SpServiceReference.getlogoimagestrResponse Sp.Service.SpServiceReference.ISpService.getlogoimagestr(Sp.Service.SpServiceReference.getlogoimagestr request) {
            return base.Channel.getlogoimagestr(request);
        }
        
        public string getlogoimagestr(string arg0, string arg1) {
            Sp.Service.SpServiceReference.getlogoimagestr inValue = new Sp.Service.SpServiceReference.getlogoimagestr();
            inValue.Body = new Sp.Service.SpServiceReference.getlogoimagestrBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            Sp.Service.SpServiceReference.getlogoimagestrResponse retVal = ((Sp.Service.SpServiceReference.ISpService)(this)).getlogoimagestr(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sp.Service.SpServiceReference.orderConfirmServiceResponse Sp.Service.SpServiceReference.ISpService.orderConfirmService(Sp.Service.SpServiceReference.orderConfirmService request) {
            return base.Channel.orderConfirmService(request);
        }
        
        public string orderConfirmService(string arg0, string arg1) {
            Sp.Service.SpServiceReference.orderConfirmService inValue = new Sp.Service.SpServiceReference.orderConfirmService();
            inValue.Body = new Sp.Service.SpServiceReference.orderConfirmServiceBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            Sp.Service.SpServiceReference.orderConfirmServiceResponse retVal = ((Sp.Service.SpServiceReference.ISpService)(this)).orderConfirmService(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sp.Service.SpServiceReference.downFinancialFileResponse Sp.Service.SpServiceReference.ISpService.downFinancialFile(Sp.Service.SpServiceReference.downFinancialFile request) {
            return base.Channel.downFinancialFile(request);
        }
        
        public string downFinancialFile(string arg0, string arg1) {
            Sp.Service.SpServiceReference.downFinancialFile inValue = new Sp.Service.SpServiceReference.downFinancialFile();
            inValue.Body = new Sp.Service.SpServiceReference.downFinancialFileBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            Sp.Service.SpServiceReference.downFinancialFileResponse retVal = ((Sp.Service.SpServiceReference.ISpService)(this)).downFinancialFile(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sp.Service.SpServiceReference.batchOrderServiceResponse Sp.Service.SpServiceReference.ISpService.batchOrderService(Sp.Service.SpServiceReference.batchOrderService request) {
            return base.Channel.batchOrderService(request);
        }
        
        public string batchOrderService(string arg0, string arg1) {
            Sp.Service.SpServiceReference.batchOrderService inValue = new Sp.Service.SpServiceReference.batchOrderService();
            inValue.Body = new Sp.Service.SpServiceReference.batchOrderServiceBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            Sp.Service.SpServiceReference.batchOrderServiceResponse retVal = ((Sp.Service.SpServiceReference.ISpService)(this)).batchOrderService(inValue);
            return retVal.Body.@return;
        }
    }
}
